version: "3"
services:
  app:
    build: .
    volumes:
      - "./app:/opt/app"
      - "./app/input:/opt/app/input"
    environment:
      #- TZ=${TZ}
      #- LANG=${LANG}
      - STARTUP_COMMAND="/usr/local/bin/start-notebook.sh"
    ports:
      - "20000:8888"