version: "3"
services:
  app:
    build: .
    volumes:
      - "./app:/opt/app"
      - "./app/input:/opt/app/input"
    command:
      - "jupyter nbconvert --to html --execute index.ipynb; rm index.html"
    ports:
      - "20000:8888"