version: "3"
services:
  app:
    build: .
    volumes:
      - "./app:/home/jovyan/work"
      - "./input:/opt/input"
    environment:
      #- TZ=${TZ}
      #- LANG=${LANG}
      - JUPYTER_TOKEN=password
    ports:
      - "20000:8888"