version: "3"
services:
  app:
    image: pudding/docker-web:docker-app-meme-pam-analyzer-app-20240128.163942
    tty: true
    volumes: 
      - "__SOURCE_INPUT__:/opt/app/input/"
      - "__SOURCE_APP__:/opt/app/"
    # restart: on-failure